### PR TITLE
Feature/using-refactor

### PR DESCRIPTION
**Pull request by AP6YC**
This PR addresses my extremely pedantic minor issue #261, breaking apart the using statements and removing duplicates.

I followed the [BlueStyle](https://github.com/invenia/BlueStyle#module-imports) since the [YAS Style](https://github.com/jrevels/YASGuide) and [Julia Formatter](https://domluna.github.io/JuliaFormatter.jl/dev/style/) don't make much mention of this sort of thing.

### CODE REVIEW

**Comment by Vaibhavdixit02** [comment]
Indeed it looks like we don't cover this point in SciMLStyle https://github.com/SciML/SciMLStyle#modules. I personally prefer having the using statements bunch up multiple packages such that those packages have some similar use in the loading package, but that said I don't have any issue with these separate using statements

**Comment by ChrisRackauckas** [comment]
Please revert. Issues of style should be settled in the style repo. And in any case, there is a clear answer here. It should use commas instead of separate usings because there are multi load optimizations in the works which would allow for invalidations to be only checked at the end of a full using statement. Therefore in the near future we may see the comma version as having a much lower load time. 

Then, in our style guide we always prefer using space instead of new lines for everything. For example, when argument numerous enough to fill more than a line, we keep things to the standard line length and then fill each subsequent line. We very specifically note that it is bad style to put one argument per line because it can make code hard to read. So extrapolating to this case, we shouldn't be doing one package per line.

We should clarify this in the style guide. And we should remove the duplicate using here. But generally the style change should be reverted.

Sorry about that, I just didn't get a chance to respond

**Comment by AP6YC** [comment]
@ChrisRackauckas Thanks so much for the reply. It was absolutely my error to not see the SciML style repo that articulates your points. Your points are very illuminating (especially about multi load optimizations, which I look forward to reading about).

@Vaibhavdixit02 I see the reasoning in grouping packages with similar use, especially in consideration of the style Chris lays out. Sorry to make more work for you in reverting the PR. I'll do more due diligence next time.

**Comment by Vaibhavdixit02** [comment]
Not at all @AP6YC, it brought up an interesting point. Please feel free to comment on the issue I created in SciMLStyle if you have anything more in mind for this

**Comment by ChrisRackauckas** [comment]
Added to the style guide https://github.com/SciML/SciMLStyle/commit/60e2ba9fdc83aea3a82887fdc319c624e525ac71 thanks!

**Pull request merged**
